config = {
  host: "https://tqda0x5aeo:ylx247b1km@jeremys-first-sandbo-9409806648.us-west-2.bonsaisearch.net",
  transport_options: {
    request: { timeout: 5 }
  },
}

if File.exists?("config/elasticsearch.yml")
  config.merge!(YAML.load_file("config/elasticsearch.yml").symbolize_keys)
end

Elasticsearch::Model.client = Elasticsearch::Client.new(config)
