config = {
  host: "https://urxefr0d:t86lei1ek6dlkqma@alder-879995.us-east-1.bonsaisearch.net",
  transport_options: {
    request: { timeout: 5 }
  },
}

if File.exists?("config/elasticsearch.yml")
  config.merge!(YAML.load_file("config/elasticsearch.yml").symbolize_keys)
end

Elasticsearch::Model.client = Elasticsearch::Client.new(config)
