# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f47c33e52b06fefd272f29d0a65e9a1e93b2fdf5fb96c5aacbcaa0bacf2dc44718127f9110099854c8bb427c4a21871a6cca86613d58830c4d9cbaa01058a0a

test:
  secret_key_base: 128add654deeeb9894ffd732cc13336fe5fac48674cc12bfd6186adbc417246c8977e7d888ac32e447e9f08cca90f03464e9a71445c37b6c3bc265539c6e79e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
