production:
  solr:
    hostname: rds-mysql-10mintutorial.chexxcbm07sw.us-west-1.rds.amazonaws.com:3306
    port: 8983
    log_level: WARNING
    path: /solr/production
    # read_timeout: 2
    # open_timeout: 0.5
development:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO
    path: /solr/development
    solr_home: solr
test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
    path: /solr/test
    